language: java
jdk:
  - openjdk11
build:
  cache: true
  cache_dir_list:
    - ~/.m2
  ci:
    - mvn install -DskipTests=true
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - mvn test
    - cp -r target/surefire-reports shippable/testresults
  post_ci:
    - [ "$IS_PULL_REQUEST" != true ] && mvn git-commit-id:revision jib:build
    - [ "$IS_PULL_REQUEST" != true ] && shipctl post_resource_state "deploy-eb-image" "latest" sha=$COMMIT


integrations:
  hub:
    - integrationName: AWS
      region: eu-west-1
      type: ecr

resources:
  - name: deploy-eb-image
    type: image
    pointer:
      sourceName: "211318693510.dkr.ecr.eu-west-1.amazonaws.com/ctl/calendar-import"
    seed:
      versionName: "latest"
  - name: deploy-eb-config
    type: cliConfig
    integration: AWS
    pointer:
      region: eu-west-1
  - name: deploy-eb-env-params
    type: params
    version:
      params:
        ENVIRONMENT: "calendar-import-dev"
        PORT: 8080
        AWS_EB_ENVIRONMENT: "calendar-import-dev"
        AWS_EB_APPLICATION: "calendar-import"

  - name: deploy-eb-repo
    type: gitRepo
    integration: github
    pointer:
      sourceName: oxctl/canvas-calendar-import
      branch: master


jobs:
  - name: canvas-calendar-import_runCI
    type: runCI
    flags:
      - deploy-eb
    steps:
      - OUT: deploy-eb-image

  - name: deploy-eb-deploy
    type: runSh
    steps:
      - IN: deploy-eb-image
      - IN: deploy-eb-config
        switch: off
      - IN: deploy-eb-env-params
        switch: off
      - IN: deploy-eb-repo
        switch: off
      - TASK:
          - script: aws elasticbeanstalk describe-applications
          - script: pushd $DEPLOYEBREPO_STATE/other && ls -al
          - script: export IMAGE="${DEPLOYEBIMAGE_SOURCENAME}:${DEPLOYEBIMAGE_VERSIONNAME}"
          - script: shippable_replace Dockerrun.aws.json .elasticbeanstalk/config.yml
          - script: eb deploy -v

