
### Configuration for S3 tests
# The S3 bucket to use
#calendar.upload.s3bucket=s3://name-ofbucket

# Set the AWS profile to use
#spring.cloud.aws.credentials.profile.name=

# Or you can directly set a key/secret
#spring.cloud.aws.credentials.access-key=
#spring.cloud.aws.credentials.secret-key=