# Is everything in debug mode?
#debug=true

# This logs request and it useful in development
logging.level.web=DEBUG
spring.http.log-request-details=true

# Disable in production
spring.mustache.cache=false

# Some logging that I've found useful in development at various points
#logging.org.springframework.beans=DEBUG
#logging.level.org.springframework.security.access.vote=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.springframework.web.client.RestTemplate=DEBUG
#logging.level.org.springframework.security.oauth2=DEBUG
#logging.level.org.apache.http=DEBUG
#logging.level.org.springframework.jdbc.datasource.init.ScriptUtils=DEBUG

# When trying to debug the SQL that is being generated
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Disable in production
# When using H2 this can be useful
# spring.h2.console.enabled=true
