# Gets used in XML LTI registration
spring.application.name=Calendar Import
spring.application.description=Provides ability to import CSV files into the calendar.

spring.mustache.enabled=true

spring.quartz.jdbc.initialize-schema=embedded
spring.quartz.job-store-type=jdbc

# The URL that the LTI launch happens for
spring.lti.launch.path=/launch

spring.data.rest.basePath=/api
# We only want a limited number of repositories to be exported
spring.data.rest.detectionStrategy=ANNOTATED

# We don't need transactions kept open in the view
spring.jpa.open-in-view=false

# The default DB
spring.datasource.url=jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=

# The fallback URLs for the CSS/JSON
calendar.common.css=https://du11hjcvx0uqb.cloudfront.net/dist/brandable_css/new_styles_normal_contrast/bundles/common-1638e73116.css
calendar.brand.json=https://du11hjcvx0uqb.cloudfront.net/dist/brandable_css/83323f307b8aa57724b3129e9742c6e2/variables-750d72b9d3e5d522f965bf904110c132.json

# Are we wanting beta features enabled.
#calendar.beta=true

