---
AWSTemplateFormatVersion: "2010-09-09"
Metadata: {}
Description: "Process to sync the production database to development/test"

Parameters:

  orgName:
    Description:  "org name used in naming"
    Type: String
    Default: "cad"
  accountType:
    Type: "String"
    Description: "production or non-production account?"
    AllowedValues:
      - "prod"
      - "nonprod"
  appName:
    Description: "Name of app"
    Type: String
  envType:
    Description: "The env type: prod, beta, test, etc"
    Type: String
    AllowedValues:
      - "prod"
      - "beta"
      - "test"
  dbSecret:
    Description: "Secret Manager ARN for the DB secret."
    Type: String
  namePrefix:
    Description: "Naming prefix for buckets"
    Type: String
  ecrTagVersion:
    Type: "String"
    Description: "The version of the dbdump/dbload code in ECR to run"
    Default: "2"
  supportEmail:
    Description: "Email for support (Cloud CAD)"
    Type: String
    Default: "cad-aws@it.ox.ac.uk"



Conditions:
  isProdEnv: {"Fn::Equals" : [!Ref envType, 'prod']}
  isBetaEnv: {"Fn::Equals" : [!Ref envType, 'beta']}
  isTestEnv: {"Fn::Equals" : [!Ref envType, 'test']}
  isProdAccount: {"Fn::Equals" : [!Ref accountType, 'prod']}
  isNonProdAccount: {"Fn::Equals" : [!Ref accountType, 'nonprod']}

Mappings:

  EnvironmentMappings:
    prod:
      "dbloadSchedule": "" #just a placeholder
    beta:
      "dbloadSchedule": "cron(0 8 ? * 1 *)" #every sunday @ 6am
      
Resources:
  ## **dbdump starts here**
  # this is to dbload to the beta env
  dbdumpFunctionBeta:
    Condition: isProdEnv
    Type: "AWS::Lambda::Function"
    Properties:
      Description: !Sub "Backup rds db for ${appName}-${envType} to a given s3 bucket prefix"
      FunctionName: !Sub "${appName}-${envType}-dbdump"
      Architectures:
        - "x86_64"
      Code:
        ImageUri:
          Fn::Sub:
            - "${repo}:dbdump.${ver}"
            - repo:
                Fn::ImportValue: !Sub "${orgName}-${accountType}-shared-ecr-repo-uri"
              ver: !Ref ecrTagVersion
      PackageType: Image
      Environment:
        Variables:
          APP_NAME: !Ref appName
          ENV_TYPE: !Ref envType
          SECRET_ID: !Ref dbSecret
          S3_BUCKET: #we want the dbdump to go into the nonprod shared S3 buckt
            Fn::Sub:
              - "${prefix}-nonprod-${region}-${accId}"
              - prefix: !Ref namePrefix
                region: !Ref 'AWS::Region'
                accId:
                  Fn::ImportValue: !Sub "${orgName}-nonprod-aws-account-id"
          BUCKET_PREFIX: !Sub "dbdump/${appName}-${envType}/"
          TO_ADDRESS: !Ref supportEmail
          FROM_ADDRESS:
            Fn::Sub:
              - "noreply@${dom}"
              - dom:
                  Fn::ImportValue: !Sub "${orgName}-${accountType}-route53-domainname"
          KEEP_DB_NAME: "Yes"
          INVOKE_DBLOAD: "Yes"
          INVOKE_DBLOAD_FUNCTION:
            Fn::Sub:
              - "arn:${awsp}:lambda:${region}:${acctid}:function:${app}-beta-dbload"
              - awsp: !Ref AWS::Partition
                region: !Ref 'AWS::Region'
                acctid:
                  Fn::ImportValue: !Sub "${orgName}-nonprod-aws-account-id"
                app: !Ref appName
          INVOKE_DBLOAD_ROLE:
            Fn::Sub:
              - "arn:${awsp}:iam::${acctid}:role/${org}-nonprod-dbload-role"
              - awsp: !Ref AWS::Partition
                acctid:
                  Fn::ImportValue: !Sub "${orgName}-nonprod-aws-account-id"
                org: !Ref orgName
      MemorySize: 256
      Role:
        Fn::ImportValue: !Sub "${orgName}-${accountType}-dbdump-xa-role-arn"
      Timeout: 300
      VpcConfig:
        SubnetIds:
          Fn::Split:
            - ","
            - Fn::ImportValue: !Sub "${orgName}-${accountType}-vpc-private-subnets"
        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${orgName}-${accountType}-lambda-sgid"
      EphemeralStorage:
        Size: 512
      LoggingConfig:
        ApplicationLogLevel: INFO
        LogFormat: JSON
        SystemLogLevel: DEBUG  #Change to info, after testing
        LogGroup: !Ref dbdumpLogGroup
  
  #logging for dbdump for all envTypes
  dbdumpLogGroup:
    Type: "AWS::Logs::LogGroup"
    Condition: isProdAccount
    Properties:
      LogGroupName: !Sub "/lambda/${appName}-${accountType}-dbdump"
      RetentionInDays: 30
  
  scheduleDBDumpToBeta:
    Condition: isProdEnv
    Type: "AWS::Scheduler::Schedule"
    Properties:
      Name: !Sub "${appName}-dbdump-to-beta-schedule"
      Description: "Schedule mysql backups to given s3 bucket"
      State: "ENABLED"
      GroupName: "default"
      ScheduleExpression: !FindInMap [ EnvironmentMappings, "beta", dbloadSchedule ]
      ScheduleExpressionTimezone: "Europe/London"
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt dbdumpFunctionBeta.Arn
        RetryPolicy:
          MaximumEventAgeInSeconds: 86400
          MaximumRetryAttempts: 0
        RoleArn:
          Fn::ImportValue: !Sub "${orgName}-${accountType}-lambda-scheduler-role-arn"
  
  ## **dbload starts here**
  #dbload for beta envType .. duplicate for more envTypes
  ##  deployed but not scheduled .. will be invoked from prod
  dbloadFunctionBeta:
    Condition: isBetaEnv
    Type: "AWS::Lambda::Function"
    Properties:
      Description: !Sub "Load rds db for ${appName}-beta from a given s3 bucket prefix"
      FunctionName: !Sub "${appName}-beta-dbload"
      Architectures:
        - "x86_64"
      Code:
        ImageUri:
          Fn::Sub:
            - "${repo}:dbload.${ver}"
            - repo:
                Fn::ImportValue: !Sub "${orgName}-${accountType}-shared-ecr-repo-uri"
              ver: !Ref ecrTagVersion
      PackageType: Image
      Environment:
        Variables:
          APP_NAME: !Ref appName
          ENV_TYPE: !Ref envType
          SECRET_ID: !Ref dbSecret
          S3_BUCKET:
            Fn::ImportValue: !Sub "${orgName}-${accountType}-shared-bucket1"
          SRC_BUCKET_PREFIX: !Sub "dbdump/${appName}-prod/"
          DEST_BUCKET_PREFIX: !Sub "dbload/${appName}-${envType}/done/"
          TO_ADDRESS: !Ref supportEmail
          FROM_ADDRESS:
            Fn::Sub:
              - "noreply@${dom}"
              - dom:
                  Fn::ImportValue: !Sub "${orgName}-${accountType}-route53-domainname"
          SAME_DB_NAME: "Yes"
      MemorySize: 256
      Role:
        Fn::ImportValue: !Sub "${orgName}-${accountType}-dbload-role-arn"
      Timeout: 30
      TracingConfig:
        Mode: "PassThrough"
      VpcConfig:
        SubnetIds:
          Fn::Split:
            - ","
            - Fn::ImportValue: !Sub "${orgName}-${accountType}-vpc-private-subnets"
        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${orgName}-${accountType}-lambda-sgid"
      EphemeralStorage:
        Size: 512
      LoggingConfig:
        ApplicationLogLevel: INFO
        LogFormat: JSON
        SystemLogLevel: DEBUG  #ToDo: Change this after testing
        LogGroup: !Ref dbloadLogGroup
  
  #logging for dbload for all envTypes
  dbloadLogGroup:
    Condition: isNonProdAccount
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/lambda/${appName}-${accountType}-dbload"
      RetentionInDays: 30 