spring.datasource.driver-class-name=com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver

# Config for AWS EB
spring.datasource.url=${SECRET_RDS}
spring.datasource.username=${SECRET_RDS}

# specify db platform (can't autodetect now that we use secrets manager jdbc wrapper)
spring.quartz.jdbc.platform=mysql

# Enable s3
spring.cloud.aws.s3.enabled=false

# Make sure we use UTF-8
spring.datasource.hikari.data-source-properties.useUnicode=true
spring.datasource.hikari.data-source-properties.characterEncoding=UTF-8
# Using a newer dialect means we default to InnoDB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
# Quartz initializing removes any existing data so we don't want to do this on production.
spring.quartz.jdbc.initialize-schema=never
spring.quartz.jdbc.comment-prefix=#

# Disable dev stuff
spring.devtools.add-properties=false

# Force the cookie to be only supplied on HTTPS connections (always the case on AWS)
server.servlet.session.cookie.secure=true

# Are we wanting to allow importing into sections
calendar.section.import=true

# As we are proxying through nginx
server.tomcat.remoteip.remote-ip-header=x-forwarded-for
server.tomcat.remoteip.protocol-header=x-forwarded-proto