# Gets used in XML LTI registration
spring.application.name=Calendar Import
spring.application.description=Provides ability to import CSV files into the calendar.
spring.quartz.job-store-type=jdbc
# Enable quartz JMX.
spring.quartz.properties.org.quartz.scheduler.jmx.export=true
# Make sure the auto created user can call the API.
spring.security.user.roles=API
spring.data.rest.basePath=/data
# We only want a limited number of repositories to be exported
spring.data.rest.detectionStrategy=ANNOTATED
# Only show 10 per page
spring.data.rest.default-page-size=10
# We don't need transactions kept open in the view
spring.jpa.open-in-view=false
# We want to swallow the whole upload, if we don't the a browser will retry the POST request because it
# got closed early. We still have an upper limit so someone can't just continually feed us data.
server.tomcat.max-swallow-size=500MB
# The default DB
spring.datasource.url=jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory
spring.jpa.properties.hibernate.cache.provider_class=org.ehcache.jsr107.EhcacheCachingProvider
spring.jpa.properties.hibernate.cache.use_query_cache=true

# These are used to validate the JWK.
jwt.issuer=https://canvas.instructure.com
jwt.jwks.uri=https://canvas.instructure.com/api/lti/security/jwks

# Setup sentry configuration
sentry.logging.minimum-event-level=warn
sentry.send-default-pii=true
