frontend.origins=*

# Config for database when using docker.
# This config file is only needed when running the application inside the docker container.
spring.datasource.url=jdbc:mysql://mysql:3306/import
spring.datasource.username=import
spring.datasource.password=import
spring.jpa.hibernate.ddl-auto=update

# Make sure we use UTF-8
spring.datasource.hikari.data-source-properties.useUnicode=true
spring.datasource.hikari.data-source-properties.characterEncoding=UTF-8

# Allows Hibernate to generate SQL optimized for a particular DBMS
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Setup quartz
spring.quartz.jdbc.initialize-schema=always
spring.quartz.jdbc.comment-prefix=#

# The issuer for the tokens when running in docker
calendar.proxy.token.issuer=https://localhost:18443