# Gets used in XML LTI registration
spring.application.name=Calendar Import
spring.application.description=Provides ability to import CSV files into the calendar.
spring.quartz.job-store-type=jdbc
# Enable quartz JMX.
spring.quartz.properties.org.quartz.scheduler.jmx.export=true
# When we start another deployment we will temporarily have 2 instances using the same DB so we need to be
# supporting clustering.
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.properties.org.quartz.jobStore.isClustered=true
spring.quartz.properties.org.quartz.jobStore.class=org.springframework.scheduling.quartz.LocalDataSourceJobStore


# Make sure the auto created user can call the API.
spring.security.user.roles=API
spring.data.rest.basePath=/data
# We only want a limited number of repositories to be exported
spring.data.rest.detectionStrategy=ANNOTATED
# Only show 10 per page
spring.data.rest.default-page-size=10
# We don't need transactions kept open in the view
spring.jpa.open-in-view=false
# We want to swallow the whole upload, if we don't the a browser will retry the POST request because it
# got closed early. We still have an upper limit so someone can't just continually feed us data.
server.tomcat.max-swallow-size=500MB
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory
spring.jpa.properties.hibernate.cache.provider_class=org.ehcache.jsr107.EhcacheCachingProvider
spring.jpa.properties.hibernate.cache.use_query_cache=true
# We need to use just a single table for sequences
spring.jpa.properties.hibernate.id.db_structure_naming_strategy=legacy

# These are used to validate the JWK.
jwt.issuer=https://canvas.instructure.com
jwt.jwks.uri=https://canvas.instructure.com/api/lti/security/jwks

# Setup sentry configuration
sentry.logging.minimum-event-level=warn
sentry.send-default-pii=true
# Send all the transactions to sentry
sentry.traces-sample-rate=1

# The maximum number of events to process in an import that is re-occuring
calendar.reimport.max.events=1000
# The interval between reimports
calendar.reimport.interval=6H
# for jobs where we abort after a number of attempts
calendar.reimport.max.retries=20

# suppress invalid token error logging as this will happen every time proxy is synced
logging.level.edu.ksu.canvas.net.SimpleRestClient=OFF

# exceptions we don't want sent to Sentry
sentry.ignored-exceptions-for-type=\
  org.springframework.security.web.firewall.RequestRejectedException,\
  org.apache.catalina.connector.ClientAbortException,\
  org.springframework.util.InvalidMimeTypeException,\
  org.springframework.http.InvalidMediaTypeException