name: Post a comment to the Azure DevOps item after merging a PR

on:
  pull_request:
    types:
      - closed
    branches:
    - master

jobs:
  post-comment:
    uses: oxctl/shared-workflows/.github/workflows/ado_comment.yml@master
    with:
      ado_organization: oxforduniversity
      ado_project: Canvas
    secrets:
      ado_username: ${{ secrets.ADO_USERNAME }}
      ado_personal_token: ${{ secrets.ADO_PERSONAL_TOKEN }}

  log-api-response:
    runs-on: ubuntu-latest
    needs: [post-comment]
    if: ${{ needs.post-comment.result == 'success' }}
    steps:
      - name: Get the API response output
        run: echo "${{ needs.post-comment.outputs.api-response }}"
