name: PR validation of CloudFormation
on:
  pull_request:
    branches: [ 'master' ]

jobs:
  validate:
    uses: oxctl/shared-workflows/.github/workflows/aws_ci.yml@master
    permissions:
      id-token: write
      contents: read
    with:
      aws_region: eu-west-1
      aws_account_id: '730335587339' # Development AWS account (cad-non-production)
      aws_role_name: cad-github-actions-role
§      timeout_minutes: 5
