# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Backend DEV

on:
  push:
    branches: [ 'master' ]
    tags: [ '*' ]
    paths:
      - 'aws/**'
      - 'backend/**'
      - '.github/workflows/backend*'
      - '.github/workflows/test_deployment*'
      - '!**/README.md'
  workflow_dispatch:

jobs:
  call-build-and-deploy:
    uses: ./.github/workflows/backend_build_and_deploy.yml
    with:
      sha: ${{ github.sha }}
      ref: ${{ github.ref }}
      do_deploy: ${{ github.ref_name == github.event.repository.default_branch }}
      aws_region: 'eu-west-1'
      aws_account_id: ${{ vars.AWS_ACCOUNT_ID_NONPROD }}
      aws_github_role: 'cad-github-actions-role'
      aws_parameters: "${{ vars.AWS_ACCOUNT_ID_NONPROD }}.json"
      github_env: 'dev'
    secrets: inherit

  call-deployment-tests:
    needs: call-build-and-deploy
    uses: ./.github/workflows/test_deployment.yml
    with:
      execution-environment: DEV
    secrets: inherit
