name: Delete Stack
run-name: "Delete ${{ inputs['stack-prefix'] }} stacks on ${{ inputs.region }} ${{ fromJson(vars.AWS_ACCOUNT_IDS_MAP)[inputs['account-id']] }}"

on:
  workflow_dispatch:
    inputs:
      stack-prefix:
        description: Prefix of stacks to remove
        type: string
        required: true
      account-id:
        description: AWS Account ID
        type: string
        required: true
      region:
        description: AWS Region
        type: string
        required: true
        default: eu-west-1


jobs:
  delete-stack:
    uses: oxctl/shared-workflows/.github/workflows/delete_stack.yml@master
    permissions:
      id-token: write
      contents: read
    with:
      stack_prefix: ${{ inputs['stack-prefix'] }}
      aws_account_id: ${{ inputs['account-id'] }}
      region: ${{ inputs.region }}
      aws_role_name: cad-github-actions-role
      frontend_export_suffix: frontend-app-bucket-name
      backend_export_suffix: backend-app-bucket-upload
      bootstrap_export_suffix: bootstrap-dist-bucket-name
      allow_prod: true
