name: Frontend Pull Request

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend*'
      - '!frontend/README.md'

jobs:
  frontend-ci:
    uses: oxctl/shared-workflows/.github/workflows/frontend_ci.yml@master
    with:
      timeout_minutes: 15
