# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend DEV

on:
  push:
    branches: [ 'master' ]
    tags: [ '*' ]
    paths:
      - 'aws/**'
      - 'frontend/**'
      - '.github/workflows/frontend*'
      - '!**/README.md'
  workflow_dispatch:

jobs:
  call-build-and-deploy:
    uses: ./.github/workflows/frontend_build_and_deploy.yml
    with:
      sha: ${{ github.sha }}
      ref: ${{ github.ref }}
      do_deploy: ${{ github.ref_name == github.event.repository.default_branch }}
      aws_region: 'eu-west-1'
      aws_account_id: '730335587339'
      aws_github_role: 'cad-github-actions-role'
      aws_parameters: '730335587339.json'
      github_env: 'dev'
      execution-environment: DEV
    secrets: inherit

  call-deployment-tests:
    needs: call-build-and-deploy
    uses: ./.github/workflows/test_deployment.yml
    with:
      execution-environment: DEV
    secrets: inherit
