name: Test Deployment
run-name: "Test deployment for the ${{ inputs.execution-environment }} environment"

on:
  workflow_call:
    inputs:
      execution-environment:
        description: "Environment"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      execution-environment:
        type: choice
        description: "Environment"
        required: true
        default: 'BETA'
        options:
          - BETA
          - PROD

jobs:
  test-deployment:
    uses: oxctl/shared-workflows/.github/workflows/test_deployment.yml@master
    with:
      execution-environment: ${{ inputs.execution-environment }}
    secrets: inherit
